repos:
  - repo: https://github.com/Exabyte-io/pre-commit-hooks
    rev: 2023.6.13
    hooks:
      - id: ruff
        exclude: ^src/py/mat3ra/esse/data
      - id: black
        exclude: ^src/py/mat3ra/esse/data
  - repo: local
    hooks:
      - id: generate-python-modules
        name: Regenerate data modules classes from static assets
        # yamllint disable rule:line-length
        entry: |
          bash -c 'if ! [ "$(git diff --cached --name-only | grep -e "example|schema")" ]; then echo "Skipping model generation because static files were not changed."; exit 0; fi'
          bash -c 'python build_schemas.py'
        # yamllint enable rule:line-length
        language: system
        pass_filenames: false
        verbose: true
