# generated by datamodel-codegen:
#   filename:  sample.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Units(Enum):
    km = "km"
    m = "m"
    cm = "cm"
    mm = "mm"
    um = "um"
    nm = "nm"
    angstrom = "angstrom"
    a_u_ = "a.u."
    bohr = "bohr"
    pm = "pm"


class Position(BaseModel):
    coordinates: List[float] = Field(..., max_length=2, min_length=2, title="array of 2 number elements schema")
    units: Units


class SampleSchema(BaseModel):
    label: str
    """
    Identity of the sample on its substrate, e.g. the grid label r0c00 of a contact pad
    """
    position: Position
    """
    Planned position of the sample in the substrate frame
    """
    id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: str
    """
    entity name
    """
    isDefault: Optional[bool] = False
    """
    Identifies that entity is defaultable
    """
    metadata: Optional[Dict[str, Any]] = None
