# generated by datamodel-codegen:
#   filename:  workflow/unit/context/item/input.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, conint


class NWChemTotalEnergyContextProviderSchema(BaseModel):
    contextProviderName: Literal["0#-datamodel-code-generator-#-object-#-special-#"]
    """
    Descriminator for AJV validator
    """
    CHARGE: int
    """
    Total charge of the system.
    """
    MULT: int
    """
    Spin multiplicity of the system.
    """
    BASIS: str
    """
    Basis set label used in the calculation (e.g., '6-31G').
    """
    NAT: int
    """
    Number of atoms in the system.
    """
    NTYP: int
    """
    Number of unique atomic species in the system.
    """
    ATOMIC_POSITIONS: str
    """
    Formatted text block with atomic positions including constraints.
    """
    ATOMIC_POSITIONS_WITHOUT_CONSTRAINTS: str
    """
    Formatted text block with atomic positions without constraints.
    """
    ATOMIC_SPECIES: str
    """
    Formatted text block for atomic species, including element symbols and masses.
    """
    FUNCTIONAL: str
    """
    Exchange-correlation functional identifier (e.g., 'B3LYP').
    """
    CARTESIAN: bool
    """
    Whether atomic positions are expressed in cartesian coordinates.
    """
    RESTART: Optional[bool] = None
    """
    Whether to continue from the RTDB of a previous run in the same working directory, taking its geometry, instead of declaring one. Optional: absent means no restart.
    """


class RESTARTMODE(Enum):
    from_scratch = "from_scratch"
    restart = "restart"


class ATOMICSPECY(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    X: str
    """
    label of the atom. Acceptable syntax: chemical symbol X (1 or 2 characters, case-insensitive) or chemical symbol plus a number or a letter, as in "Xn" (e.g. Fe1) or "X_*" or "X-*" (e.g. C1, C_h; max total length cannot exceed 3 characters)
    """
    Mass_X: float
    """
    mass of the atomic species [amu: mass of C = 12]. Used only when performing Molecular Dynamics run or structural optimization runs using Damped MD. Not actually used in all other cases (but stored in data files, so phonon calculations will use these values unless other values are provided)
    """
    PseudoPot_X: str
    """
    PseudoPot_X
    """


class ATOMICSPECIESWITHLABEL(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    X: str
    """
    label of the atom. Acceptable syntax: chemical symbol X (1 or 2 characters, case-insensitive) or chemical symbol plus a number or a letter, as in "Xn" (e.g. Fe1) or "X_*" or "X-*" (e.g. C1, C_h; max total length cannot exceed 3 characters)
    """
    Mass_X: float
    """
    mass of the atomic species [amu: mass of C = 12]. Used only when performing Molecular Dynamics run or structural optimization runs using Damped MD. Not actually used in all other cases (but stored in data files, so phonon calculations will use these values unless other values are provided)
    """
    PseudoPot_X: str
    """
    PseudoPot_X
    """


class ATOMICPOSITION(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    X: Optional[str] = None
    """
    label of the atom as specified in ATOMIC_SPECIES
    """
    x: float
    """
    atomic positions
    """
    y: float
    """
    atomic positions
    """
    z: float
    """
    atomic positions
    """
    if_pos_1_: Optional[conint(ge=0, le=1)] = Field(None, alias="if_pos(1)", title="integer one or zero")
    if_pos_2_: Optional[conint(ge=0, le=1)] = Field(None, alias="if_pos(2)", title="integer one or zero")
    if_pos_3_: Optional[conint(ge=0, le=1)] = Field(None, alias="if_pos(3)", title="integer one or zero")


class CELLPARAMETERS(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    v1: Optional[List[float]] = Field(None, max_length=3, min_length=3, title="array of 3 number elements schema")
    v2: Optional[List[float]] = Field(None, max_length=3, min_length=3, title="array of 3 number elements schema")
    v3: Optional[List[float]] = Field(None, max_length=3, min_length=3, title="array of 3 number elements schema")


class FIRSTIMAGEItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    X: Optional[str] = None
    """
    label of the atom as specified in ATOMIC_SPECIES
    """
    x: float
    """
    atomic positions
    """
    y: float
    """
    atomic positions
    """
    z: float
    """
    atomic positions
    """
    if_pos_1_: Optional[conint(ge=0, le=1)] = Field(None, alias="if_pos(1)", title="integer one or zero")
    if_pos_2_: Optional[conint(ge=0, le=1)] = Field(None, alias="if_pos(2)", title="integer one or zero")
    if_pos_3_: Optional[conint(ge=0, le=1)] = Field(None, alias="if_pos(3)", title="integer one or zero")


class LASTIMAGEItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    X: Optional[str] = None
    """
    label of the atom as specified in ATOMIC_SPECIES
    """
    x: float
    """
    atomic positions
    """
    y: float
    """
    atomic positions
    """
    z: float
    """
    atomic positions
    """
    if_pos_1_: Optional[conint(ge=0, le=1)] = Field(None, alias="if_pos(1)", title="integer one or zero")
    if_pos_2_: Optional[conint(ge=0, le=1)] = Field(None, alias="if_pos(2)", title="integer one or zero")
    if_pos_3_: Optional[conint(ge=0, le=1)] = Field(None, alias="if_pos(3)", title="integer one or zero")


class INTERMEDIATEIMAGE(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    X: Optional[str] = None
    """
    label of the atom as specified in ATOMIC_SPECIES
    """
    x: float
    """
    atomic positions
    """
    y: float
    """
    atomic positions
    """
    z: float
    """
    atomic positions
    """
    if_pos_1_: Optional[conint(ge=0, le=1)] = Field(None, alias="if_pos(1)", title="integer one or zero")
    if_pos_2_: Optional[conint(ge=0, le=1)] = Field(None, alias="if_pos(2)", title="integer one or zero")
    if_pos_3_: Optional[conint(ge=0, le=1)] = Field(None, alias="if_pos(3)", title="integer one or zero")


class QENEBContextProviderSchema(BaseModel):
    IBRAV: int
    RESTART_MODE: Optional[RESTARTMODE] = "from_scratch"
    ATOMIC_SPECIES: List[ATOMICSPECY]
    ATOMIC_SPECIES_WITH_LABELS: List[ATOMICSPECIESWITHLABEL]
    NAT: int
    """
    number of atoms in the unit cell (ALL atoms, except if space_group is set, in which case, INEQUIVALENT atoms)
    """
    NTYP: int
    """
    number of types of atoms in the unit cell
    """
    NTYP_WITH_LABELS: conint(ge=1)
    """
    Number of different atomic species including labels
    """
    ATOMIC_POSITIONS: Optional[List[ATOMICPOSITION]] = None
    ATOMIC_POSITIONS_WITHOUT_CONSTRAINTS: Optional[str] = None
    """
    Formatted text block for ATOMIC_POSITIONS card WITHOUT constraints. Format: 'X x y z' per line
    """
    CELL_PARAMETERS: CELLPARAMETERS
    FIRST_IMAGE: List[FIRSTIMAGEItem]
    LAST_IMAGE: List[LASTIMAGEItem]
    INTERMEDIATE_IMAGES: List[List[INTERMEDIATEIMAGE]]
    """
    Atomic positions blocks (ATOMIC_POSITIONS) for all intermediate NEB images.
    """
    contextProviderName: Literal["1#-datamodel-code-generator-#-object-#-special-#"]
    """
    Descriminator for AJV validator
    """


class QEPwxContextProviderSchema(BaseModel):
    IBRAV: int
    RESTART_MODE: Optional[RESTARTMODE] = "from_scratch"
    ATOMIC_SPECIES: List[ATOMICSPECY]
    ATOMIC_SPECIES_WITH_LABELS: List[ATOMICSPECIESWITHLABEL]
    NAT: int
    """
    number of atoms in the unit cell (ALL atoms, except if space_group is set, in which case, INEQUIVALENT atoms)
    """
    NTYP: int
    """
    number of types of atoms in the unit cell
    """
    NTYP_WITH_LABELS: conint(ge=1)
    """
    Number of different atomic species including labels
    """
    ATOMIC_POSITIONS: List[ATOMICPOSITION]
    ATOMIC_POSITIONS_WITHOUT_CONSTRAINTS: str
    """
    Formatted text block for ATOMIC_POSITIONS card WITHOUT constraints. Format: 'X x y z' per line
    """
    CELL_PARAMETERS: CELLPARAMETERS
    contextProviderName: Literal["2#-datamodel-code-generator-#-object-#-special-#"]
    """
    Descriminator for AJV validator
    """


class VASPContextProviderSchema(BaseModel):
    POSCAR: str
    """
    POSCAR content for VASP including lattice, atom types, positions and constraints.
    """
    POSCAR_WITH_CONSTRAINTS: str
    """
    POSCAR content for VASP including lattice, atom types, positions and constraints. May differ in how constraints are represented.
    """
    contextProviderName: Literal["3#-datamodel-code-generator-#-object-#-special-#"]
    """
    Descriminator for AJV validator
    """


class VASPNEBContextProviderSchema(BaseModel):
    FIRST_IMAGE: str
    """
    POSCAR content with constraints for the first NEB image.
    """
    LAST_IMAGE: str
    """
    POSCAR content with constraints for the last NEB image.
    """
    INTERMEDIATE_IMAGES: List[str]
    """
    POSCAR contents with constraints for all intermediate NEB images.
    """
    contextProviderName: Literal["4#-datamodel-code-generator-#-object-#-special-#"]
    """
    Descriminator for AJV validator
    """


class ExtraDataWithMaterialHashSchema(BaseModel):
    materialHash: Optional[str] = None
    """
    UI only property used to track material change for re-render
    """


class InputContextItemSchema(BaseModel):
    name: Literal["input"]
    data: Union[
        NWChemTotalEnergyContextProviderSchema,
        QENEBContextProviderSchema,
        QEPwxContextProviderSchema,
        VASPContextProviderSchema,
        VASPNEBContextProviderSchema,
    ] = Field(..., discriminator="contextProviderName")
    extraData: ExtraDataWithMaterialHashSchema = Field(..., title="extraData with materialHash schema")
    isEdited: bool
