# generated by datamodel-codegen:
#   filename:  context_providers_directory/by_application/nwchem_total_energy_context_provider.json
#   version:   0.28.5

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel


class NWChemTotalEnergyContextProviderSchema(BaseModel):
    contextProviderName: Literal["nwchem-total-energy"]
    """
    Descriminator for AJV validator
    """
    CHARGE: int
    """
    Total charge of the system.
    """
    MULT: int
    """
    Spin multiplicity of the system.
    """
    BASIS: str
    """
    Basis set label used in the calculation (e.g., '6-31G').
    """
    NAT: int
    """
    Number of atoms in the system.
    """
    NTYP: int
    """
    Number of unique atomic species in the system.
    """
    ATOMIC_POSITIONS: str
    """
    Formatted text block with atomic positions including constraints.
    """
    ATOMIC_POSITIONS_WITHOUT_CONSTRAINTS: str
    """
    Formatted text block with atomic positions without constraints.
    """
    ATOMIC_SPECIES: str
    """
    Formatted text block for atomic species, including element symbols and masses.
    """
    FUNCTIONAL: str
    """
    Exchange-correlation functional identifier (e.g., 'B3LYP').
    """
    CARTESIAN: bool
    """
    Whether atomic positions are expressed in cartesian coordinates.
    """
    RESTART: Optional[bool] = None
    """
    Whether to continue from the RTDB of a previous run in the same working directory, taking its geometry, instead of declaring one. Optional: absent means no restart.
    """
