# generated by datamodel-codegen:
#   filename:  properties_directory/enum_options.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import RootModel


class ESSE(RootModel[Any]):
    root: Any


class ExternalSource(Enum):
    ICSD = "ICSD"
    MaterialsProject = "MaterialsProject"
    MaterialsProjectLegacy = "MaterialsProjectLegacy"


class PropertyType(Enum):
    scalar = "scalar"
    non_scalar = "non-scalar"
    tensor = "tensor"
    object = "object"
    array_of_objects = "array-of-objects"


class ScalarPropertyEnum(Enum):
    defect_formation_energy = "defect_formation_energy"
    fermi_energy = "fermi_energy"
    formation_energy = "formation_energy"
    homo_energy = "homo_energy"
    ionization_potential = "ionization_potential"
    lumo_energy = "lumo_energy"
    pressure = "pressure"
    reaction_energy_barrier = "reaction_energy_barrier"
    surface_energy = "surface_energy"
    interfacial_energy = "interfacial_energy"
    thermal_correction_to_energy = "thermal_correction_to_energy"
    thermal_correction_to_enthalpy = "thermal_correction_to_enthalpy"
    total_energy = "total_energy"
    total_force = "total_force"
    valence_band_offset = "valence_band_offset"
    zero_point_energy = "zero_point_energy"


class NonScalarPropertyEnum(Enum):
    average_potential_profile = "average_potential_profile"
    band_gaps = "band_gaps"
    band_structure = "band_structure"
    charge_density_profile = "charge_density_profile"
    convergence_electronic = "convergence_electronic"
    convergence_ionic = "convergence_ionic"
    density_of_states = "density_of_states"
    dielectric_tensor = "dielectric_tensor"
    file_content = "file_content"
    final_structure = "final_structure"
    hubbard_u = "hubbard_u"
    hubbard_v = "hubbard_v"
    hubbard_v_nn = "hubbard_v_nn"
    hysteresis_loop = "hysteresis_loop"
    is_relaxed = "is_relaxed"
    jupyter_notebook_endpoint = "jupyter_notebook_endpoint"
    phonon_dispersions = "phonon_dispersions"
    phonon_dos = "phonon_dos"
    potential_profile = "potential_profile"
    reaction_energy_profile = "reaction_energy_profile"
    wavefunction_amplitude = "wavefunction_amplitude"
    workflow_pyml_predict = "workflow:pyml_predict"


class TensorPropertyEnum(Enum):
    atomic_forces = "atomic_forces"
    magnetic_moments = "magnetic_moments"
    stress_tensor = "stress_tensor"


class ObjectPropertyEnum(Enum):
    total_energy_contributions = "total_energy_contributions"


class ArrayOfObjectsPropertyEnum(Enum):
    formation_energy_contributions = "formation_energy_contributions"


class ProtoPropertyEnum(Enum):
    atomic_constraints = "atomic_constraints"
    boundary_conditions = "boundary_conditions"


class MetaPropertyEnum(Enum):
    pseudopotential = "pseudopotential"
