# generated by datamodel-codegen:
#   filename:  properties_directory/non_scalar/hysteresis_loop.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, Field


class Label(Enum):
    bias = "bias"


class Units(Enum):
    V = "V"
    mV = "mV"


class AxisSchema(BaseModel):
    label: Label
    """
    label of an axis object
    """
    units: Optional[Units] = None
    """
    units for an axis
    """


class Label29(Enum):
    response = "response"


class Units265(Enum):
    km = "km"
    m = "m"
    cm = "cm"
    mm = "mm"
    um = "um"
    nm = "nm"
    angstrom = "angstrom"
    a_u_ = "a.u."
    bohr = "bohr"
    pm = "pm"


class AxisSchema32(BaseModel):
    label: Label29
    """
    label of an axis object
    """
    units: Optional[Units265] = None
    """
    units for an axis
    """


class Name(Enum):
    hysteresis_loop = "hysteresis_loop"


class FieldConditionSchema(Enum):
    on = "on"
    off = "off"


class CombinedValueSchema(BaseModel):
    value: float
    """
    mean over the combined measurements
    """
    standardDeviation: float
    """
    population standard deviation over the combined measurements (not the standard error of the mean)
    """
    count: int
    """
    number of measurements combined
    """


class CoerciveVoltage(BaseModel):
    rising: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    A value combined over repeated measurements: mean, standard deviation, count. Units come from the context the value appears in
    """
    falling: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    A value combined over repeated measurements: mean, standard deviation, count. Units come from the context the value appears in
    """


class RemanentResponse(BaseModel):
    rising: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    A value combined over repeated measurements: mean, standard deviation, count. Units come from the context the value appears in
    """
    falling: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    A value combined over repeated measurements: mean, standard deviation, count. Units come from the context the value appears in
    """


class HysteresisLoopParametersSchema(BaseModel):
    imprint: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    bias at the centre of the loop: half the sum of the two coercive voltages
    """
    coerciveVoltage: CoerciveVoltage
    """
    bias at which the response crosses the loop's offset, on the rising and the falling branch
    """
    loopWidth: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    bias separation of the two coercive voltages
    """
    loopHeight: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    response separation of the two remanent responses
    """
    remanentResponse: RemanentResponse
    """
    response at zero bias, on the rising and the falling branch
    """


class CoerciveVoltage3(BaseModel):
    rising: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    A value combined over repeated measurements: mean, standard deviation, count. Units come from the context the value appears in
    """
    falling: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    A value combined over repeated measurements: mean, standard deviation, count. Units come from the context the value appears in
    """


class RemanentResponse3(BaseModel):
    rising: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    A value combined over repeated measurements: mean, standard deviation, count. Units come from the context the value appears in
    """
    falling: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    A value combined over repeated measurements: mean, standard deviation, count. Units come from the context the value appears in
    """


class HysteresisLoopParametersSchema3(BaseModel):
    imprint: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    bias at the centre of the loop: half the sum of the two coercive voltages
    """
    coerciveVoltage: CoerciveVoltage3
    """
    bias at which the response crosses the loop's offset, on the rising and the falling branch
    """
    loopWidth: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    bias separation of the two coercive voltages
    """
    loopHeight: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    response separation of the two remanent responses
    """
    remanentResponse: RemanentResponse3
    """
    response at zero bias, on the rising and the falling branch
    """


class Parameters(BaseModel):
    on: HysteresisLoopParametersSchema = Field(..., title="Hysteresis loop parameters schema")
    """
    Parameters read from a hysteresis loop, each combined over the loops measured at one field condition. Voltages are in the loop's xAxis units, responses in its yAxis units
    """
    off: HysteresisLoopParametersSchema3 = Field(..., title="Hysteresis loop parameters schema")
    """
    Parameters read from a hysteresis loop, each combined over the loops measured at one field condition. Voltages are in the loop's xAxis units, responses in its yAxis units
    """


class HysteresisLoopPropertySchema(BaseModel):
    xAxis: AxisSchema = Field(..., title="axis schema")
    yAxis: AxisSchema32 = Field(..., title="axis schema")
    name: Name
    legend: List[FieldConditionSchema]
    """
    the field condition of each series in yDataSeries
    """
    parameters: Parameters
    """
    parameters read from the loop of each field condition; their voltages are in xAxis units and their responses in yAxis units
    """
    xDataArray: List[Union[float, List[float]]]
    """
    array containing values of x Axis
    """
    yDataSeries: List[List[float]] = Field(..., title="1 dimension data series schema")
