# generated by datamodel-codegen:
#   filename:  properties_directory/non_scalar/phonon_dispersions.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, Field


class Label(Enum):
    qpoints = "qpoints"


class Units(Enum):
    crystal = "crystal"
    cartesian = "cartesian"


class AxisSchema(BaseModel):
    label: Label
    """
    label of an axis object
    """
    units: Optional[Units] = "crystal"
    """
    units for an axis
    """


class Label31(Enum):
    frequency = "frequency"


class Units319(Enum):
    cm_1 = "cm-1"
    THz = "THz"
    meV = "meV"


class AxisSchema34(BaseModel):
    label: Label31
    """
    label of an axis object
    """
    units: Optional[Units319] = None
    """
    units for an axis
    """


class Name(Enum):
    phonon_dispersions = "phonon_dispersions"


class PhononBandStructurePropertySchema(BaseModel):
    xAxis: AxisSchema = Field(..., title="axis schema")
    yAxis: AxisSchema34 = Field(..., title="axis schema")
    name: Name
    xDataArray: List[Union[float, List[float]]]
    """
    array containing values of x Axis
    """
    yDataSeries: List[List[float]] = Field(..., title="1 dimension data series schema")
