# generated by datamodel-codegen:
#   filename:  properties_directory/non_scalar/phonon_dos.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, Field


class Label(Enum):
    frequency = "frequency"


class Units(Enum):
    cm_1 = "cm-1"
    THz = "THz"
    meV = "meV"


class AxisSchema(BaseModel):
    label: Label
    """
    label of an axis object
    """
    units: Optional[Units] = None
    """
    units for an axis
    """


class Label33(Enum):
    Phonon_DOS = "Phonon DOS"


class Units321(Enum):
    states_cm_1 = "states/cm-1"
    states_THz = "states/THz"
    states_meV = "states/meV"


class AxisSchema36(BaseModel):
    label: Label33
    """
    label of an axis object
    """
    units: Optional[Units321] = None
    """
    units for an axis
    """


class Name(Enum):
    phonon_dos = "phonon_dos"


class PhononDensityOfStatesPropertySchema(BaseModel):
    xAxis: AxisSchema = Field(..., title="axis schema")
    yAxis: AxisSchema36 = Field(..., title="axis schema")
    name: Name
    xDataArray: List[Union[float, List[float]]]
    """
    array containing values of x Axis
    """
    yDataSeries: List[List[float]] = Field(..., title="1 dimension data series schema")
