# generated by datamodel-codegen:
#   filename:  properties_directory/non_scalar/total_energy_contributions.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Name(Enum):
    temperature_entropy = "temperature_entropy"


class ScalarSchema(BaseModel):
    name: Optional[Name] = None
    value: float


class Name845(Enum):
    harris_foulkes = "harris_foulkes"


class ScalarSchema104(BaseModel):
    name: Optional[Name845] = None
    value: float


class Name846(Enum):
    smearing = "smearing"


class ScalarSchema105(BaseModel):
    name: Optional[Name846] = None
    value: float


class Name847(Enum):
    one_electron = "one_electron"


class ScalarSchema106(BaseModel):
    name: Optional[Name847] = None
    value: float


class Name848(Enum):
    hartree = "hartree"


class ScalarSchema107(BaseModel):
    name: Optional[Name848] = None
    value: float


class Name849(Enum):
    exchange = "exchange"


class ScalarSchema108(BaseModel):
    name: Optional[Name849] = None
    value: float


class Name850(Enum):
    exchange_correlation = "exchange_correlation"


class ScalarSchema109(BaseModel):
    name: Optional[Name850] = None
    value: float


class Name851(Enum):
    ewald = "ewald"


class ScalarSchema110(BaseModel):
    name: Optional[Name851] = None
    value: float


class Name852(Enum):
    alphaZ = "alphaZ"


class ScalarSchema111(BaseModel):
    name: Optional[Name852] = None
    value: float


class Name853(Enum):
    atomic_energy = "atomic_energy"


class ScalarSchema112(BaseModel):
    name: Optional[Name853] = None
    value: float


class Name854(Enum):
    eigenvalues = "eigenvalues"


class ScalarSchema113(BaseModel):
    name: Optional[Name854] = None
    value: float


class Name855(Enum):
    PAW_double_counting_correction_2 = "PAW_double-counting_correction_2"


class ScalarSchema114(BaseModel):
    name: Optional[Name855] = None
    value: float


class Name856(Enum):
    PAW_double_counting_correction_3 = "PAW_double-counting_correction_3"


class ScalarSchema115(BaseModel):
    name: Optional[Name856] = None
    value: float


class Name857(Enum):
    hartree_fock = "hartree_fock"


class ScalarSchema116(BaseModel):
    name: Optional[Name857] = None
    value: float


class Name858(Enum):
    total_energy_contributions = "total_energy_contributions"


class Units(Enum):
    kcal_mol = "kcal/mol"
    kJ_mol = "kJ/mol"
    eV = "eV"
    J_mol = "J/mol"
    hartree = "hartree"
    cm_1 = "cm-1"
    Ry = "Ry"
    eV_atom = "eV/atom"


class TotalEnergyContributionsPropertySchema(BaseModel):
    temperatureEntropy: Optional[ScalarSchema] = Field(None, title="scalar schema")
    """
    product of temperature and configurational entropy
    """
    harris_foulkes: Optional[ScalarSchema104] = Field(None, title="scalar schema")
    """
    non self-consitent energy based on an input charge density
    """
    smearing: Optional[ScalarSchema105] = Field(None, title="scalar schema")
    """
    smearing energy
    """
    one_electron: Optional[ScalarSchema106] = Field(None, title="scalar schema")
    """
    kinetic + pseudopotential energy
    """
    hartree: Optional[ScalarSchema107] = Field(None, title="scalar schema")
    """
    energy due to coulomb potential
    """
    exchange: Optional[ScalarSchema108] = Field(None, title="scalar schema")
    """
    exchange energy
    """
    exchange_correlation: Optional[ScalarSchema109] = Field(None, title="scalar schema")
    """
    exchange and correlation energy per particle
    """
    ewald: Optional[ScalarSchema110] = Field(None, title="scalar schema")
    """
    summation of interaction energies at long length scales due to coloumbic interactions
    """
    alphaZ: Optional[ScalarSchema111] = Field(None, title="scalar schema")
    """
    divergent electrostatic ion interaction in compensating electron gas
    """
    atomicEnergy: Optional[ScalarSchema112] = Field(None, title="scalar schema")
    """
    kinetic energy of wavefunctions in the atomic limit
    """
    eigenvalues: Optional[ScalarSchema113] = Field(None, title="scalar schema")
    """
    sum of one electron energies of kinetic, electrostatic, and exchange correlation
    """
    PAWDoubleCounting2: Optional[ScalarSchema114] = Field(None, title="scalar schema")
    """
    double counting correction 2
    """
    PAWDoubleCounting3: Optional[ScalarSchema115] = Field(None, title="scalar schema")
    """
    double counting correction 3
    """
    hartreeFock: Optional[ScalarSchema116] = Field(None, title="scalar schema")
    """
    hartree-fock contribution
    """
    name: Name858
    units: Optional[Units] = None
