# generated by datamodel-codegen:
#   filename:  properties_directory/non_scalar/wavefunction_amplitude.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, Field


class Label(Enum):
    coordinate = "coordinate"


class AxisSchema(BaseModel):
    label: Label
    """
    label of an axis object
    """
    units: Optional[str] = None
    """
    units for an axis
    """


class Label41(Enum):
    amplitude = "amplitude"


class AxisSchema44(BaseModel):
    label: Label41
    """
    label of an axis object
    """
    units: Optional[str] = None
    """
    units for an axis
    """


class Name(Enum):
    wavefunction_amplitude = "wavefunction_amplitude"


class WavefunctionAmplitudePropertySchema(BaseModel):
    xAxis: AxisSchema = Field(..., title="axis schema")
    yAxis: AxisSchema44 = Field(..., title="axis schema")
    name: Name
    xDataArray: List[Union[float, List[float]]]
    """
    array containing values of x Axis
    """
    yDataSeries: List[List[float]] = Field(..., title="1 dimension data series schema")
