# generated by datamodel-codegen:
#   filename:  properties_directory/non_scalar/workflow.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel, confloat, conint


class Name(Enum):
    workflow_pyml_predict = "workflow:pyml_predict"


class Queue(Enum):
    D = "D"
    OR = "OR"
    OF = "OF"
    OFplus = "OFplus"
    SR = "SR"
    SF = "SF"
    SFplus = "SFplus"
    OR4 = "OR4"
    OR8 = "OR8"
    OR16 = "OR16"
    SR4 = "SR4"
    SR8 = "SR8"
    SR16 = "SR16"
    GOF = "GOF"
    G4OF = "G4OF"
    G8OF = "G8OF"
    GSF = "GSF"
    G4SF = "G4SF"
    G8SF = "G8SF"


class TimeLimitType(Enum):
    per_single_attempt = "per single attempt"
    compound = "compound"


class QuantumEspressoArgumentsSchema(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    nimage: Optional[conint(ge=1, le=100)] = 1
    """
    Processors can be divided into different `images`, each corresponding to a different self-consistent or linear-response calculation, loosely coupled to others.
    """
    npools: Optional[conint(ge=1, le=100)] = 1
    """
    Each image can be subpartitioned into `pools`, each taking care of a group of k-points.
    """
    nband: Optional[conint(ge=1, le=100)] = 1
    """
    Each pool is subpartitioned into `band groups`, each taking care of a group of Kohn-Sham orbitals (also called bands, or wavefunctions).
    """
    ntg: Optional[conint(ge=1, le=100)] = 1
    """
    In order to allow good parallelization of the 3D FFT when the number of processors exceeds the number of FFT planes, FFTs on Kohn-Sham states are redistributed to `task` groups so that each group can process several wavefunctions at the same time.
    """
    ndiag: Optional[conint(ge=1, le=100)] = 1
    """
    A further level of parallelization, independent on PW or k-point parallelization, is the parallelization of subspace diagonalization / iterative orthonormalization. Both operations required the diagonalization of arrays whose dimension is the number of Kohn-Sham states (or a small multiple of it). All such arrays are distributed block-like across the `linear-algebra group`, a subgroup of the pool of processors, organized in a square 2D grid. As a consequence the number of processors in the linear-algebra group is given by n2, where n is an integer; n2 must be smaller than the number of processors in the PW group. The diagonalization is then performed in parallel using standard linear algebra operations.
    """


class Cluster(BaseModel):
    fqdn: Optional[str] = None
    """
    FQDN of the cluster. e.g. master-1-staging.exabyte.io
    """
    jid: Optional[str] = None
    """
    Job's identity in RMS. e.g. 1234.master-1-staging.exabyte.io
    """


class Domain(Enum):
    rupy = "rupy"
    alfred = "alfred"
    celim = "celim"
    webapp = "webapp"


class Error(BaseModel):
    domain: Optional[Domain] = None
    """
    Domain of the error appearance (internal).
    """
    reason: Optional[str] = None
    """
    Should be a short, unique, machine-readable error code string. e.g. FileNotFound
    """
    message: Optional[str] = None
    """
    Human-readable error message. e.g. 'File Not Found: /home/demo/data/project1/job-123/job-config.json'
    """
    traceback: Optional[str] = None
    """
    Full machine-readable error traceback. e.g. FileNotFound
    """


class ComputeArgumentsSchema(BaseModel):
    queue: Queue
    """
    Name of the submission queues: https://docs.mat3ra.com/infrastructure/resource/queues/. Below enums are for Azure, then AWS circa 2022-08, hence the duplication.
    """
    nodes: int
    """
    number of nodes used for the job inside the RMS.
    """
    ppn: int
    """
    number of CPUs used for the job inside the RMS.
    """
    timeLimit: str
    """
    Wallclock time limit for computing a job. Clock format: 'hh:mm:ss'
    """
    timeLimitType: Optional[TimeLimitType] = "per single attempt"
    """
    Convention to use when reasoning about time limits
    """
    isRestartable: Optional[bool] = True
    """
    Job is allowed to restart on termination.
    """
    notify: Optional[str] = None
    """
    Email notification for the job: n - never, a - job aborted, b - job begins, e - job ends. Last three could be combined.
    """
    email: Optional[str] = None
    """
    Email address to notify about job execution.
    """
    maxCPU: Optional[int] = None
    """
    Maximum CPU count per node. This parameter is used to let backend job submission infrastructure know that this job is to be charged for the maximum CPU per node instead of the actual ppn. For premium/fast queues where resources are provisioned on-demand and exclusively per user.
    """
    arguments: Optional[QuantumEspressoArgumentsSchema] = Field({}, title="quantum espresso arguments schema")
    """
    Optional arguments specific to using application - VASP, Quantum Espresso, etc. Specified elsewhere
    """
    cluster: Optional[Cluster] = None
    """
    Cluster where the job is executed. Optional on create. Required on job submission.
    """
    errors: Optional[List[Error]] = None
    """
    Computation error. Optional. Appears only if something happens on jobs execution.
    """
    excludeFilesPattern: Optional[str] = None
    """
    A Python compatible regex to exclude files from upload. e.g. ^.*.txt& excludes all files with .txt suffix
    """


class Error17(BaseModel):
    domain: Optional[Domain] = None
    """
    Domain of the error appearance (internal).
    """
    reason: Optional[str] = None
    """
    Should be a short, unique, machine-readable error code string. e.g. FileNotFound
    """
    message: Optional[str] = None
    """
    Human-readable error message. e.g. 'File Not Found: /home/demo/data/project1/job-123/job-config.json'
    """
    traceback: Optional[str] = None
    """
    Full machine-readable error traceback. e.g. FileNotFound
    """


class ComputeArgumentsSchema17(BaseModel):
    queue: Queue
    """
    Name of the submission queues: https://docs.mat3ra.com/infrastructure/resource/queues/. Below enums are for Azure, then AWS circa 2022-08, hence the duplication.
    """
    nodes: int
    """
    number of nodes used for the job inside the RMS.
    """
    ppn: int
    """
    number of CPUs used for the job inside the RMS.
    """
    timeLimit: str
    """
    Wallclock time limit for computing a job. Clock format: 'hh:mm:ss'
    """
    timeLimitType: Optional[TimeLimitType] = "per single attempt"
    """
    Convention to use when reasoning about time limits
    """
    isRestartable: Optional[bool] = True
    """
    Job is allowed to restart on termination.
    """
    notify: Optional[str] = None
    """
    Email notification for the job: n - never, a - job aborted, b - job begins, e - job ends. Last three could be combined.
    """
    email: Optional[str] = None
    """
    Email address to notify about job execution.
    """
    maxCPU: Optional[int] = None
    """
    Maximum CPU count per node. This parameter is used to let backend job submission infrastructure know that this job is to be charged for the maximum CPU per node instead of the actual ppn. For premium/fast queues where resources are provisioned on-demand and exclusively per user.
    """
    arguments: Optional[QuantumEspressoArgumentsSchema] = Field({}, title="quantum espresso arguments schema")
    """
    Optional arguments specific to using application - VASP, Quantum Espresso, etc. Specified elsewhere
    """
    cluster: Optional[Cluster] = None
    """
    Cluster where the job is executed. Optional on create. Required on job submission.
    """
    errors: Optional[List[Error17]] = None
    """
    Computation error. Optional. Appears only if something happens on jobs execution.
    """
    excludeFilesPattern: Optional[str] = None
    """
    A Python compatible regex to exclude files from upload. e.g. ^.*.txt& excludes all files with .txt suffix
    """


class RuntimeItemNameObjectSchema(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str
    """
    The name of this item. e.g. scf_accuracy
    """


class StatusTrackItem(BaseModel):
    trackedAt: float
    status: str
    repetition: Optional[float] = None


class Status(Enum):
    idle = "idle"
    active = "active"
    warning = "warning"
    error = "error"
    finished = "finished"


class Subtype(Enum):
    input = "input"
    output = "output"
    dataFrame = "dataFrame"


class Source(Enum):
    api = "api"
    object_storage = "object_storage"


class DataIORestAPIInputSchema(BaseModel):
    type: Literal["0#-datamodel-code-generator-#-object-#-special-#"]
    endpoint: str
    """
    rest API endpoint
    """
    endpoint_options: Dict[str, Any]
    """
    rest API endpoint options
    """
    name: Optional[str] = None
    """
    the name of the variable in local scope to save the data under
    """


class ObjectStorageContainerData(BaseModel):
    CONTAINER: Optional[str] = None
    """
    Object storage container for the file
    """
    NAME: Optional[str] = None
    """
    Name of the file inside the object storage bucket
    """
    PROVIDER: Optional[str] = None
    """
    Object storage provider
    """
    REGION: Optional[str] = None
    """
    Region for the object container specified in Container
    """
    SIZE: Optional[int] = None
    """
    Size of the file in bytes
    """
    TIMESTAMP: Optional[str] = None
    """
    Unix timestamp showing when the file was last modified
    """


class ObjectStorageIoSchema(BaseModel):
    type: Literal["1#-datamodel-code-generator-#-object-#-special-#"]
    objectData: ObjectStorageContainerData = Field(..., title="Object Storage Container Data")
    overwrite: Optional[bool] = None
    """
    if a file with the same filename already exists, whether to overwrite the old file
    """
    pathname: Optional[str] = None
    """
    Relative path to the directory that contains the file.
    """
    basename: Optional[str] = None
    """
    Basename of the file
    """
    filetype: Optional[str] = None
    """
    What kind of file this is, e.g. image / text
    """


class Input(RootModel[Union[DataIORestAPIInputSchema, ObjectStorageIoSchema]]):
    root: Union[DataIORestAPIInputSchema, ObjectStorageIoSchema] = Field(..., discriminator="type")


class DataIOUnitSchema(BaseModel):
    id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: str
    """
    entity name
    """
    isDefault: Optional[bool] = False
    """
    Identifies that entity is defaultable
    """
    preProcessors: List[RuntimeItemNameObjectSchema]
    """
    names of the pre-processors for this calculation
    """
    postProcessors: List[RuntimeItemNameObjectSchema]
    """
    names of the post-processors for this calculation
    """
    monitors: List[RuntimeItemNameObjectSchema]
    """
    names of the monitors for this calculation
    """
    results: List[RuntimeItemNameObjectSchema]
    """
    names of the results for this calculation
    """
    tags: Optional[List[str]] = None
    """
    entity tags
    """
    statusTrack: Optional[List[StatusTrackItem]] = None
    isDraft: Optional[bool] = None
    head: Optional[bool] = None
    """
    Whether this unit is the first one to be executed.
    """
    flowchartId: str
    """
    Identity of the unit in the workflow. Used to trace the execution flow of the workflow.
    """
    next: Optional[str] = None
    """
    Next unit's flowchartId. If empty, the current unit is the last.
    """
    enableRender: Optional[bool] = None
    """
    Whether Rupy should attempt to use Jinja templating to add context variables into the unit
    """
    status: Optional[Status] = None
    """
    Status of the unit.
    """
    type: Literal["0#-datamodel-code-generator-#-object-#-special-#"]
    subtype: Subtype
    source: Source
    input: List[Input]


class WorkflowUnitInputSchema(BaseModel):
    scope: str
    """
    Scope of the variable. e.g. 'global' or 'flowchart_id_2'
    """
    name: str
    """
    Name of the input data. e.g. total_energy
    """


class ConditionUnitSchema(BaseModel):
    id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: str
    """
    entity name
    """
    isDefault: Optional[bool] = False
    """
    Identifies that entity is defaultable
    """
    preProcessors: List[RuntimeItemNameObjectSchema]
    """
    names of the pre-processors for this calculation
    """
    postProcessors: List[RuntimeItemNameObjectSchema]
    """
    names of the post-processors for this calculation
    """
    monitors: List[RuntimeItemNameObjectSchema]
    """
    names of the monitors for this calculation
    """
    results: List[RuntimeItemNameObjectSchema]
    """
    names of the results for this calculation
    """
    tags: Optional[List[str]] = None
    """
    entity tags
    """
    statusTrack: Optional[List[StatusTrackItem]] = None
    isDraft: Optional[bool] = None
    head: Optional[bool] = None
    """
    Whether this unit is the first one to be executed.
    """
    flowchartId: str
    """
    Identity of the unit in the workflow. Used to trace the execution flow of the workflow.
    """
    next: Optional[str] = None
    """
    Next unit's flowchartId. If empty, the current unit is the last.
    """
    enableRender: Optional[bool] = None
    """
    Whether Rupy should attempt to use Jinja templating to add context variables into the unit
    """
    status: Optional[Status] = None
    """
    Status of the unit.
    """
    type: Literal["1#-datamodel-code-generator-#-object-#-special-#"]
    input: List[WorkflowUnitInputSchema]
    """
    Input information for condition.
    """
    statement: str
    """
    Condition statement. e.g. 'abs(x-total_energy) < 1e-5'
    """
    then: str
    """
    Flowchart ID reference for `then` part of the condition.
    """
    else_: str = Field(..., alias="else")
    """
    Flowchart ID reference for `else` part of the condition.
    """
    maxOccurrences: int
    """
    Maximum occurrence of the condition, usable for loops.
    """
    throwException: Optional[bool] = None
    """
    Throw exception on reaching to maximum occurence.
    """


class AssertionUnitSchema(BaseModel):
    id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: str
    """
    entity name
    """
    isDefault: Optional[bool] = False
    """
    Identifies that entity is defaultable
    """
    preProcessors: List[RuntimeItemNameObjectSchema]
    """
    names of the pre-processors for this calculation
    """
    postProcessors: List[RuntimeItemNameObjectSchema]
    """
    names of the post-processors for this calculation
    """
    monitors: List[RuntimeItemNameObjectSchema]
    """
    names of the monitors for this calculation
    """
    results: List[RuntimeItemNameObjectSchema]
    """
    names of the results for this calculation
    """
    tags: Optional[List[str]] = None
    """
    entity tags
    """
    statusTrack: Optional[List[StatusTrackItem]] = None
    isDraft: Optional[bool] = None
    head: Optional[bool] = None
    """
    Whether this unit is the first one to be executed.
    """
    flowchartId: str
    """
    Identity of the unit in the workflow. Used to trace the execution flow of the workflow.
    """
    next: Optional[str] = None
    """
    Next unit's flowchartId. If empty, the current unit is the last.
    """
    enableRender: Optional[bool] = None
    """
    Whether Rupy should attempt to use Jinja templating to add context variables into the unit
    """
    status: Optional[Status] = None
    """
    Status of the unit.
    """
    type: Literal["2#-datamodel-code-generator-#-object-#-special-#"]
    statement: str
    """
    The statement to be evaluated
    """
    errorMessage: Optional[str] = None
    """
    The error message to be displayed if the assertion fails
    """


class RunConfig(BaseModel):
    commandTemplate: str
    """
    The command template of the application
    """
    outFileName: str
    """
    The output file name of the application
    """


class ApplicationSchema(BaseModel):
    id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: str
    """
    entity name
    """
    isDefault: Optional[bool] = False
    """
    Identifies that entity is defaultable
    """
    shortName: str
    """
    The short name of the application. e.g. qe
    """
    summary: str
    """
    Application's short description.
    """
    version: str
    """
    Application version. e.g. 5.3.5
    """
    build: str
    """
    Application build. e.g. VTST
    """
    isDefaultVersion: Optional[bool] = None
    """
    Whether the version is the default version
    """
    hasAdvancedComputeOptions: Optional[bool] = None
    """
    Whether advanced compute options are present
    """
    isLicensed: Optional[bool] = None
    """
    Whether licensing is present
    """
    isUsingMaterial: Optional[bool] = None
    """
    Whether the application is using (being passed during a downstream processing routine) a material structure.
    """
    runConfig: Optional[RunConfig] = None
    """
    The run configuration of the application
    """


class NamedDefaultableInMemoryEntitySchema(BaseModel):
    id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: str
    """
    entity name
    """
    isDefault: Optional[bool] = False
    """
    Identifies that entity is defaultable
    """
    applicationName: str
    """
    name of the application this executable belongs to
    """
    applicationVersion: str
    """
    version of the application this executable belongs to
    """
    hasAdvancedComputeOptions: Optional[bool] = None
    """
    Whether advanced compute options are present
    """


class ExecutionUnitInputIdItemSchemaForPhysicsBasedSimulationEngines(BaseModel):
    templateId: Optional[str] = None
    templateName: Optional[str] = None
    name: str
    """
    name of the resulting input file, if different than template name
    """


class FlavorSchema(BaseModel):
    id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: str
    """
    entity name
    """
    isDefault: Optional[bool] = False
    """
    Identifies that entity is defaultable
    """
    preProcessors: List[RuntimeItemNameObjectSchema]
    """
    names of the pre-processors for this calculation
    """
    postProcessors: List[RuntimeItemNameObjectSchema]
    """
    names of the post-processors for this calculation
    """
    monitors: List[RuntimeItemNameObjectSchema]
    """
    names of the monitors for this calculation
    """
    results: List[RuntimeItemNameObjectSchema]
    """
    names of the results for this calculation
    """
    executableName: str
    """
    name of the executable this flavor belongs to
    """
    applicationName: str
    """
    name of the application this flavor belongs to
    """
    applicationVersion: str
    """
    version of the application this flavor belongs to
    """
    input: List[ExecutionUnitInputIdItemSchemaForPhysicsBasedSimulationEngines] = Field(
        ..., title="execution unit input schema"
    )


class ContextProvider(BaseModel):
    name: str


class TemplateSchema(BaseModel):
    id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: str
    """
    entity name
    """
    executableName: str
    applicationName: str
    applicationVersion: str
    contextProviders: List[ContextProvider]
    content: str
    """
    Content of the template. e.g. &CONTROL    calculation='scf' ...
    """


class ExecutionUnitInputItemSchema(BaseModel):
    template: TemplateSchema = Field(..., title="template schema")
    rendered: Optional[str] = None
    """
    Rendered content of the input file. e.g. &CONTROL    calculation='scf' ...
    """
    isManuallyChanged: Optional[bool] = False


class NWChemTotalEnergyContextProviderSchema(BaseModel):
    contextProviderName: Literal["0#-datamodel-code-generator-#-object-#-special-#"]
    """
    Descriminator for AJV validator
    """
    CHARGE: int
    """
    Total charge of the system.
    """
    MULT: int
    """
    Spin multiplicity of the system.
    """
    BASIS: str
    """
    Basis set label used in the calculation (e.g., '6-31G').
    """
    NAT: int
    """
    Number of atoms in the system.
    """
    NTYP: int
    """
    Number of unique atomic species in the system.
    """
    ATOMIC_POSITIONS: str
    """
    Formatted text block with atomic positions including constraints.
    """
    ATOMIC_POSITIONS_WITHOUT_CONSTRAINTS: str
    """
    Formatted text block with atomic positions without constraints.
    """
    ATOMIC_SPECIES: str
    """
    Formatted text block for atomic species, including element symbols and masses.
    """
    FUNCTIONAL: str
    """
    Exchange-correlation functional identifier (e.g., 'B3LYP').
    """
    CARTESIAN: bool
    """
    Whether atomic positions are expressed in cartesian coordinates.
    """
    RESTART: Optional[bool] = None
    """
    Whether to continue from the RTDB of a previous run in the same working directory, taking its geometry, instead of declaring one. Optional: absent means no restart.
    """


class RESTARTMODE(Enum):
    from_scratch = "from_scratch"
    restart = "restart"


class ATOMICSPECY(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    X: str
    """
    label of the atom. Acceptable syntax: chemical symbol X (1 or 2 characters, case-insensitive) or chemical symbol plus a number or a letter, as in "Xn" (e.g. Fe1) or "X_*" or "X-*" (e.g. C1, C_h; max total length cannot exceed 3 characters)
    """
    Mass_X: float
    """
    mass of the atomic species [amu: mass of C = 12]. Used only when performing Molecular Dynamics run or structural optimization runs using Damped MD. Not actually used in all other cases (but stored in data files, so phonon calculations will use these values unless other values are provided)
    """
    PseudoPot_X: str
    """
    PseudoPot_X
    """


class ATOMICSPECIESWITHLABEL(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    X: str
    """
    label of the atom. Acceptable syntax: chemical symbol X (1 or 2 characters, case-insensitive) or chemical symbol plus a number or a letter, as in "Xn" (e.g. Fe1) or "X_*" or "X-*" (e.g. C1, C_h; max total length cannot exceed 3 characters)
    """
    Mass_X: float
    """
    mass of the atomic species [amu: mass of C = 12]. Used only when performing Molecular Dynamics run or structural optimization runs using Damped MD. Not actually used in all other cases (but stored in data files, so phonon calculations will use these values unless other values are provided)
    """
    PseudoPot_X: str
    """
    PseudoPot_X
    """


class ATOMICPOSITION(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    X: Optional[str] = None
    """
    label of the atom as specified in ATOMIC_SPECIES
    """
    x: float
    """
    atomic positions
    """
    y: float
    """
    atomic positions
    """
    z: float
    """
    atomic positions
    """
    if_pos_1_: Optional[conint(ge=0, le=1)] = Field(None, alias="if_pos(1)", title="integer one or zero")
    if_pos_2_: Optional[conint(ge=0, le=1)] = Field(None, alias="if_pos(2)", title="integer one or zero")
    if_pos_3_: Optional[conint(ge=0, le=1)] = Field(None, alias="if_pos(3)", title="integer one or zero")


class CELLPARAMETERS(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    v1: Optional[List[float]] = Field(None, max_length=3, min_length=3, title="array of 3 number elements schema")
    v2: Optional[List[float]] = Field(None, max_length=3, min_length=3, title="array of 3 number elements schema")
    v3: Optional[List[float]] = Field(None, max_length=3, min_length=3, title="array of 3 number elements schema")


class FIRSTIMAGEItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    X: Optional[str] = None
    """
    label of the atom as specified in ATOMIC_SPECIES
    """
    x: float
    """
    atomic positions
    """
    y: float
    """
    atomic positions
    """
    z: float
    """
    atomic positions
    """
    if_pos_1_: Optional[conint(ge=0, le=1)] = Field(None, alias="if_pos(1)", title="integer one or zero")
    if_pos_2_: Optional[conint(ge=0, le=1)] = Field(None, alias="if_pos(2)", title="integer one or zero")
    if_pos_3_: Optional[conint(ge=0, le=1)] = Field(None, alias="if_pos(3)", title="integer one or zero")


class LASTIMAGEItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    X: Optional[str] = None
    """
    label of the atom as specified in ATOMIC_SPECIES
    """
    x: float
    """
    atomic positions
    """
    y: float
    """
    atomic positions
    """
    z: float
    """
    atomic positions
    """
    if_pos_1_: Optional[conint(ge=0, le=1)] = Field(None, alias="if_pos(1)", title="integer one or zero")
    if_pos_2_: Optional[conint(ge=0, le=1)] = Field(None, alias="if_pos(2)", title="integer one or zero")
    if_pos_3_: Optional[conint(ge=0, le=1)] = Field(None, alias="if_pos(3)", title="integer one or zero")


class INTERMEDIATEIMAGE(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    X: Optional[str] = None
    """
    label of the atom as specified in ATOMIC_SPECIES
    """
    x: float
    """
    atomic positions
    """
    y: float
    """
    atomic positions
    """
    z: float
    """
    atomic positions
    """
    if_pos_1_: Optional[conint(ge=0, le=1)] = Field(None, alias="if_pos(1)", title="integer one or zero")
    if_pos_2_: Optional[conint(ge=0, le=1)] = Field(None, alias="if_pos(2)", title="integer one or zero")
    if_pos_3_: Optional[conint(ge=0, le=1)] = Field(None, alias="if_pos(3)", title="integer one or zero")


class QENEBContextProviderSchema(BaseModel):
    IBRAV: int
    RESTART_MODE: Optional[RESTARTMODE] = "from_scratch"
    ATOMIC_SPECIES: List[ATOMICSPECY]
    ATOMIC_SPECIES_WITH_LABELS: List[ATOMICSPECIESWITHLABEL]
    NAT: int
    """
    number of atoms in the unit cell (ALL atoms, except if space_group is set, in which case, INEQUIVALENT atoms)
    """
    NTYP: int
    """
    number of types of atoms in the unit cell
    """
    NTYP_WITH_LABELS: conint(ge=1)
    """
    Number of different atomic species including labels
    """
    ATOMIC_POSITIONS: Optional[List[ATOMICPOSITION]] = None
    ATOMIC_POSITIONS_WITHOUT_CONSTRAINTS: Optional[str] = None
    """
    Formatted text block for ATOMIC_POSITIONS card WITHOUT constraints. Format: 'X x y z' per line
    """
    CELL_PARAMETERS: CELLPARAMETERS
    FIRST_IMAGE: List[FIRSTIMAGEItem]
    LAST_IMAGE: List[LASTIMAGEItem]
    INTERMEDIATE_IMAGES: List[List[INTERMEDIATEIMAGE]]
    """
    Atomic positions blocks (ATOMIC_POSITIONS) for all intermediate NEB images.
    """
    contextProviderName: Literal["1#-datamodel-code-generator-#-object-#-special-#"]
    """
    Descriminator for AJV validator
    """


class QEPwxContextProviderSchema(BaseModel):
    IBRAV: int
    RESTART_MODE: Optional[RESTARTMODE] = "from_scratch"
    ATOMIC_SPECIES: List[ATOMICSPECY]
    ATOMIC_SPECIES_WITH_LABELS: List[ATOMICSPECIESWITHLABEL]
    NAT: int
    """
    number of atoms in the unit cell (ALL atoms, except if space_group is set, in which case, INEQUIVALENT atoms)
    """
    NTYP: int
    """
    number of types of atoms in the unit cell
    """
    NTYP_WITH_LABELS: conint(ge=1)
    """
    Number of different atomic species including labels
    """
    ATOMIC_POSITIONS: List[ATOMICPOSITION]
    ATOMIC_POSITIONS_WITHOUT_CONSTRAINTS: str
    """
    Formatted text block for ATOMIC_POSITIONS card WITHOUT constraints. Format: 'X x y z' per line
    """
    CELL_PARAMETERS: CELLPARAMETERS
    contextProviderName: Literal["2#-datamodel-code-generator-#-object-#-special-#"]
    """
    Descriminator for AJV validator
    """


class VASPContextProviderSchema(BaseModel):
    POSCAR: str
    """
    POSCAR content for VASP including lattice, atom types, positions and constraints.
    """
    POSCAR_WITH_CONSTRAINTS: str
    """
    POSCAR content for VASP including lattice, atom types, positions and constraints. May differ in how constraints are represented.
    """
    contextProviderName: Literal["3#-datamodel-code-generator-#-object-#-special-#"]
    """
    Descriminator for AJV validator
    """


class VASPNEBContextProviderSchema(BaseModel):
    FIRST_IMAGE: str
    """
    POSCAR content with constraints for the first NEB image.
    """
    LAST_IMAGE: str
    """
    POSCAR content with constraints for the last NEB image.
    """
    INTERMEDIATE_IMAGES: List[str]
    """
    POSCAR contents with constraints for all intermediate NEB images.
    """
    contextProviderName: Literal["4#-datamodel-code-generator-#-object-#-special-#"]
    """
    Descriminator for AJV validator
    """


class ExtraDataWithMaterialHashSchema(BaseModel):
    materialHash: Optional[str] = None
    """
    UI only property used to track material change for re-render
    """


class InputContextItemSchema(BaseModel):
    name: Literal["0#-datamodel-code-generator-#-object-#-special-#"]
    data: Union[
        NWChemTotalEnergyContextProviderSchema,
        QENEBContextProviderSchema,
        QEPwxContextProviderSchema,
        VASPContextProviderSchema,
        VASPNEBContextProviderSchema,
    ] = Field(..., discriminator="contextProviderName")
    extraData: ExtraDataWithMaterialHashSchema = Field(..., title="extraData with materialHash schema")
    isEdited: bool


class PlanewaveCutoffsContextProviderSchema(BaseModel):
    wavefunction: Optional[float] = None
    density: Optional[float] = None


class CutoffsContextItemSchema(BaseModel):
    name: Literal["1#-datamodel-code-generator-#-object-#-special-#"]
    data: PlanewaveCutoffsContextProviderSchema = Field(..., title="Planewave Cutoffs Context Provider Schema")
    """
    Planewave cutoff parameters for electronic wavefunctions and density. Units are specific to simulation engine.
    """
    isEdited: bool
    extraData: Dict[str, Any]


class Name894(Enum):
    kgrid = "kgrid"
    qgrid = "qgrid"
    igrid = "igrid"


class GridMetricType(Enum):
    KPPRA = "KPPRA"
    spacing = "spacing"


class PointsGridDataProviderSchema(BaseModel):
    dimensions: Union[List[float], List[str]]
    shifts: Optional[List[float]] = Field(None, max_length=3, min_length=3)
    reciprocalVectorRatios: Optional[List[float]] = Field(None, max_length=3, min_length=3)
    gridMetricType: GridMetricType
    gridMetricValue: float
    preferGridMetric: Optional[bool] = None


class GridContextItemSchema(BaseModel):
    name: Literal["2#-datamodel-code-generator-#-object-#-special-#"]
    data: PointsGridDataProviderSchema = Field(..., title="Points Grid Data Provider Schema")
    """
    3D grid with shifts for k-point or q-point sampling.
    """
    extraData: ExtraDataWithMaterialHashSchema = Field(..., title="extraData with materialHash schema")
    isEdited: bool


class Name895(Enum):
    qpath = "qpath"
    ipath = "ipath"
    kpath = "kpath"
    explicitKPath = "explicitKPath"
    explicitKPath2PIBA = "explicitKPath2PIBA"


class PointsPathDataProviderSchemaItem(BaseModel):
    point: str
    steps: float


class PathContextItemSchema(BaseModel):
    name: Literal["3#-datamodel-code-generator-#-object-#-special-#"]
    data: List[PointsPathDataProviderSchemaItem] = Field(..., min_length=1, title="Points Path Data Provider Schema")
    """
    Path in reciprocal space for band structure calculations. User-editable and persisted fields only (coordinates are derived at render time).
    """
    extraData: ExtraDataWithMaterialHashSchema = Field(..., title="extraData with materialHash schema")
    isEdited: bool


class Species(Enum):
    U = "U"
    J = "J"
    B = "B"
    E2 = "E2"
    E3 = "E3"


class HubbardJContextProviderSchemaItem(BaseModel):
    paramType: Optional[Species] = Field(None, title="Species")
    atomicSpecies: Optional[str] = Field(None, title="Species")
    atomicOrbital: Optional[str] = Field(None, title="Orbital")
    value: Optional[float] = Field(None, title="Value (eV)")


class HubbardJContextItemSchema(BaseModel):
    name: Literal["4#-datamodel-code-generator-#-object-#-special-#"]
    data: List[HubbardJContextProviderSchemaItem] = Field(..., min_length=1, title="Hubbard J Context Provider Schema")
    """
    Hubbard parameters for DFT+U+J calculation.
    """
    isEdited: bool
    extraData: Dict[str, Any]


class HubbardUContextProviderSchemaItem(BaseModel):
    atomicSpecies: Optional[str] = Field(None, title="Atomic species")
    atomicOrbital: Optional[str] = Field(None, title="Atomic orbital")
    hubbardUValue: Optional[float] = Field(None, title="Hubbard U (eV)")


class HubbardUContextItemSchema(BaseModel):
    name: Literal["5#-datamodel-code-generator-#-object-#-special-#"]
    data: List[HubbardUContextProviderSchemaItem] = Field(..., title="Hubbard U Context Provider Schema")
    """
    Hubbard U parameters for DFT+U or DFT+U+V calculation.
    """
    extraData: ExtraDataWithMaterialHashSchema = Field(..., title="extraData with materialHash schema")
    isEdited: bool


class HubbardVContextProviderSchemaItem(BaseModel):
    atomicSpecies: Optional[str] = Field(None, title="Species 1")
    siteIndex: Optional[int] = Field(None, title="Site no 1")
    atomicOrbital: Optional[str] = Field(None, title="Orbital 1")
    atomicSpecies2: Optional[str] = Field(None, title="Species 2")
    siteIndex2: Optional[int] = Field(None, title="Site no 2")
    atomicOrbital2: Optional[str] = Field(None, title="Orbital 2")
    hubbardVValue: Optional[float] = Field(None, title="V (eV)")


class HubbardVContextItemSchema(BaseModel):
    name: Literal["6#-datamodel-code-generator-#-object-#-special-#"]
    data: List[HubbardVContextProviderSchemaItem] = Field(..., min_length=1, title="Hubbard V Context Provider Schema")
    """
    Hubbard V parameters for DFT+U+V calculation.
    """
    isEdited: bool
    extraData: Dict[str, Any]


class HubbardLegacyContextProviderSchemaItem(BaseModel):
    atomicSpecies: Optional[str] = Field(None, title="Atomic species")
    atomicSpeciesIndex: Optional[int] = Field(None, title="Species index")
    hubbardUValue: Optional[float] = Field(None, title="Hubbard U (eV)")


class HubbardLegacyContextItemSchema(BaseModel):
    name: Literal["7#-datamodel-code-generator-#-object-#-special-#"]
    data: List[HubbardLegacyContextProviderSchemaItem] = Field(
        ..., min_length=1, title="Hubbard Legacy Context Provider Schema"
    )
    """
    Hubbard parameters for DFT+U calculation.
    """
    isEdited: bool
    extraData: Dict[str, Any]


class NEBDataProviderSchema(BaseModel):
    nImages: Optional[float] = None


class NebContextItemSchema(BaseModel):
    name: Literal["8#-datamodel-code-generator-#-object-#-special-#"]
    data: NEBDataProviderSchema = Field(..., title="NEB Data Provider Schema")
    """
    Number of intermediate NEB images.
    """
    isEdited: bool
    extraData: Dict[str, Any]


class Type(Enum):
    pbc = "pbc"
    bc1 = "bc1"
    bc2 = "bc2"
    bc3 = "bc3"


class BoundaryConditionsDataProviderSchema(BaseModel):
    type: Optional[Type] = "pbc"
    """
    If assume_isolated = 'esm', determines the boundary conditions used for either side of the slab.
    """
    offset: Optional[float] = None
    electricField: Optional[float] = Field(None, title="Electric Field (eV/A)")
    targetFermiEnergy: Optional[float] = Field(None, title="Target Fermi Energy (eV)")


class BoundaryConditionsContextItemSchema(BaseModel):
    name: Literal["9#-datamodel-code-generator-#-object-#-special-#"]
    data: BoundaryConditionsDataProviderSchema = Field(..., title="Boundary Conditions Data Provider Schema")
    extraData: ExtraDataWithMaterialHashSchema = Field(..., title="extraData with materialHash schema")
    isEdited: bool


class ProblemCategory(Enum):
    regression = "regression"
    classification = "classification"
    clustering = "clustering"


class MLSettingsContextProviderSchema(BaseModel):
    target_column_name: Optional[str] = None
    problem_category: Optional[ProblemCategory] = None


class MlSettingsContextItemSchema(BaseModel):
    name: Literal["10#-datamodel-code-generator-#-object-#-special-#"]
    data: MLSettingsContextProviderSchema = Field(..., title="ML Settings Context Provider Schema")
    """
    Settings important to machine learning runs.
    """
    isEdited: bool
    extraData: Dict[str, Any]


class MLTrainTestSplitContextProviderSchema(BaseModel):
    fraction_held_as_test_set: Optional[confloat(ge=0.0, le=1.0)] = None


class MlTrainTestSplitContextItemSchema(BaseModel):
    name: Literal["11#-datamodel-code-generator-#-object-#-special-#"]
    data: MLTrainTestSplitContextProviderSchema = Field(..., title="ML Train Test Split Context Provider Schema")
    """
    Fraction held as the test set. For example, a value of 0.2 corresponds to an 80/20 train/test split.
    """
    isEdited: bool
    extraData: Dict[str, Any]


class IonDynamicsContextProviderSchema(BaseModel):
    numberOfSteps: Optional[int] = Field(None, title="numberOfSteps")
    timeStep: Optional[float] = Field(None, title="timeStep (Hartree a.u.)")
    electronMass: Optional[float] = Field(None, title="Effective electron mass")
    temperature: Optional[float] = Field(None, title="Ionic temperature (K)")


class DynamicsContextItemSchema(BaseModel):
    name: Literal["12#-datamodel-code-generator-#-object-#-special-#"]
    data: IonDynamicsContextProviderSchema = Field(..., title="Ion Dynamics Context Provider Schema")
    """
    Important parameters for molecular dynamics calculation
    """
    isEdited: bool
    extraData: Dict[str, Any]


class StartingMagnetizationItem(BaseModel):
    atomicSpecies: str = Field(..., title="Atomic species")
    value: confloat(ge=-1.0, le=1.0) = Field(..., title="Starting magnetization")
    index: int = Field(..., title="Index")


class CollinearMagnetizationContextProviderSchema(BaseModel):
    startingMagnetization: List[StartingMagnetizationItem]
    isTotalMagnetization: bool = Field(..., title="Set total magnetization instead")
    totalMagnetization: float = Field(..., title="Total magnetization")


class CollinearMagnetizationContextItemSchema(BaseModel):
    name: Literal["13#-datamodel-code-generator-#-object-#-special-#"]
    data: CollinearMagnetizationContextProviderSchema = Field(
        ..., title="Collinear Magnetization Context Provider Schema"
    )
    """
    Set starting magnetization, can have values in the range [-1, +1].
    """
    extraData: ExtraDataWithMaterialHashSchema = Field(..., title="extraData with materialHash schema")
    isEdited: bool


class StartingMagnetizationItem31(BaseModel):
    index: Optional[int] = Field(None, title="Index")
    atomicSpecies: Optional[str] = Field(None, title="Atomic species")
    value: Optional[float] = Field(None, title="Starting magnetization")


class SpinAngle(BaseModel):
    index: Optional[int] = Field(None, title="Index")
    atomicSpecies: Optional[str] = Field(None, title="Atomic species")
    angle1: Optional[float] = Field(None, title="Angle1 (deg)")
    angle2: Optional[float] = Field(None, title="Angle2 (deg)")


class ConstrainType(Enum):
    none = "none"
    total = "total"
    atomic = "atomic"
    total_direction = "total direction"
    atomic_direction = "atomic direction"


class ConstrainedMagnetization(BaseModel):
    constrainType: Optional[ConstrainType] = Field(None, title="Constrain type")
    lambda_: Optional[float] = Field(None, alias="lambda", title="lambda")


class FixedMagnetization(BaseModel):
    x: Optional[float] = Field(None, title="X-component")
    y: Optional[float] = Field(None, title="Y-component")
    z: Optional[float] = Field(None, title="Z-component")


class NonCollinearMagnetizationContextProviderSchema(BaseModel):
    isExistingChargeDensity: Optional[bool] = Field(None, title="Use existing charge density")
    isStartingMagnetization: Optional[bool] = Field(None, title="Set starting magnetization")
    startingMagnetization: Optional[List[StartingMagnetizationItem31]] = None
    isArbitrarySpinAngle: Optional[bool] = Field(None, title="Set arbitrary spin angle")
    isArbitrarySpinDirection: Optional[bool] = Field(None, title="Set arbitrary spin direction")
    lforcet: Optional[bool] = None
    spinAngles: Optional[List[SpinAngle]] = None
    isConstrainedMagnetization: Optional[bool] = Field(None, title="Set constrained magnetization")
    constrainedMagnetization: Optional[ConstrainedMagnetization] = None
    isFixedMagnetization: Optional[bool] = Field(
        None, title="Set Fixed magnetization (only applicable to constrained magnetization of 'total' type)"
    )
    fixedMagnetization: Optional[FixedMagnetization] = None


class NonCollinearMagnetizationContextItemSchema(BaseModel):
    name: Literal["14#-datamodel-code-generator-#-object-#-special-#"]
    data: NonCollinearMagnetizationContextProviderSchema = Field(
        ..., title="Non Collinear Magnetization Context Provider Schema"
    )
    """
    Non-collinear magnetization parameters including starting magnetization, spin angles, and constraints.
    """
    extraData: ExtraDataWithMaterialHashSchema = Field(..., title="extraData with materialHash schema")
    isEdited: bool


class ContextItemSchema(
    RootModel[
        Union[
            InputContextItemSchema,
            CutoffsContextItemSchema,
            GridContextItemSchema,
            PathContextItemSchema,
            HubbardJContextItemSchema,
            HubbardUContextItemSchema,
            HubbardVContextItemSchema,
            HubbardLegacyContextItemSchema,
            NebContextItemSchema,
            BoundaryConditionsContextItemSchema,
            MlSettingsContextItemSchema,
            MlTrainTestSplitContextItemSchema,
            DynamicsContextItemSchema,
            CollinearMagnetizationContextItemSchema,
            NonCollinearMagnetizationContextItemSchema,
        ]
    ]
):
    root: Union[
        InputContextItemSchema,
        CutoffsContextItemSchema,
        GridContextItemSchema,
        PathContextItemSchema,
        HubbardJContextItemSchema,
        HubbardUContextItemSchema,
        HubbardVContextItemSchema,
        HubbardLegacyContextItemSchema,
        NebContextItemSchema,
        BoundaryConditionsContextItemSchema,
        MlSettingsContextItemSchema,
        MlTrainTestSplitContextItemSchema,
        DynamicsContextItemSchema,
        CollinearMagnetizationContextItemSchema,
        NonCollinearMagnetizationContextItemSchema,
    ] = Field(..., discriminator="name", title="context item schema")


class ExecutionUnitSchema(BaseModel):
    id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: str
    """
    entity name
    """
    isDefault: Optional[bool] = False
    """
    Identifies that entity is defaultable
    """
    preProcessors: List[RuntimeItemNameObjectSchema]
    """
    names of the pre-processors for this calculation
    """
    postProcessors: List[RuntimeItemNameObjectSchema]
    """
    names of the post-processors for this calculation
    """
    monitors: List[RuntimeItemNameObjectSchema]
    """
    names of the monitors for this calculation
    """
    results: List[RuntimeItemNameObjectSchema]
    """
    names of the results for this calculation
    """
    tags: Optional[List[str]] = None
    """
    entity tags
    """
    statusTrack: Optional[List[StatusTrackItem]] = None
    isDraft: Optional[bool] = None
    head: Optional[bool] = None
    """
    Whether this unit is the first one to be executed.
    """
    flowchartId: str
    """
    Identity of the unit in the workflow. Used to trace the execution flow of the workflow.
    """
    next: Optional[str] = None
    """
    Next unit's flowchartId. If empty, the current unit is the last.
    """
    enableRender: Optional[bool] = None
    """
    Whether Rupy should attempt to use Jinja templating to add context variables into the unit
    """
    status: Optional[Status] = None
    """
    Status of the unit.
    """
    type: Literal["3#-datamodel-code-generator-#-object-#-special-#"]
    application: ApplicationSchema = Field(..., title="application schema")
    executable: NamedDefaultableInMemoryEntitySchema = Field(..., title="Named defaultable in-memory entity schema")
    flavor: FlavorSchema = Field(..., title="flavor schema")
    input: List[ExecutionUnitInputItemSchema]
    context: Optional[List[ContextItemSchema]] = []


class AssignmentUnitSchema(BaseModel):
    id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: str
    """
    entity name
    """
    isDefault: Optional[bool] = False
    """
    Identifies that entity is defaultable
    """
    preProcessors: List[RuntimeItemNameObjectSchema]
    """
    names of the pre-processors for this calculation
    """
    postProcessors: List[RuntimeItemNameObjectSchema]
    """
    names of the post-processors for this calculation
    """
    monitors: List[RuntimeItemNameObjectSchema]
    """
    names of the monitors for this calculation
    """
    results: List[RuntimeItemNameObjectSchema]
    """
    names of the results for this calculation
    """
    tags: Optional[List[str]] = None
    """
    entity tags
    """
    statusTrack: Optional[List[StatusTrackItem]] = None
    isDraft: Optional[bool] = None
    head: Optional[bool] = None
    """
    Whether this unit is the first one to be executed.
    """
    flowchartId: str
    """
    Identity of the unit in the workflow. Used to trace the execution flow of the workflow.
    """
    next: Optional[str] = None
    """
    Next unit's flowchartId. If empty, the current unit is the last.
    """
    enableRender: Optional[bool] = None
    """
    Whether Rupy should attempt to use Jinja templating to add context variables into the unit
    """
    status: Optional[Status] = None
    """
    Status of the unit.
    """
    scope: Optional[str] = None
    type: Literal["4#-datamodel-code-generator-#-object-#-special-#"]
    input: List[WorkflowUnitInputSchema]
    """
    Input information for assignment. if omitted, means that it is an initialization unit, otherwise it is an assignment.
    """
    operand: str
    """
    Name of the global variable. e.g. 'x'
    """
    value: Union[str, bool, float]
    """
    Value of the variable. The value content could be a simple integer, string or a python expression. e.g. '0' (initialization), 'sin(x)+1' (expression)
    """


class ErrorUnitSchema(BaseModel):
    id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: str
    """
    entity name
    """
    isDefault: Optional[bool] = False
    """
    Identifies that entity is defaultable
    """
    preProcessors: List[RuntimeItemNameObjectSchema]
    """
    names of the pre-processors for this calculation
    """
    postProcessors: List[RuntimeItemNameObjectSchema]
    """
    names of the post-processors for this calculation
    """
    monitors: List[RuntimeItemNameObjectSchema]
    """
    names of the monitors for this calculation
    """
    results: List[RuntimeItemNameObjectSchema]
    """
    names of the results for this calculation
    """
    tags: Optional[List[str]] = None
    """
    entity tags
    """
    statusTrack: Optional[List[StatusTrackItem]] = None
    isDraft: Optional[bool] = None
    head: Optional[bool] = None
    """
    Whether this unit is the first one to be executed.
    """
    flowchartId: str
    """
    Identity of the unit in the workflow. Used to trace the execution flow of the workflow.
    """
    next: Optional[str] = None
    """
    Next unit's flowchartId. If empty, the current unit is the last.
    """
    enableRender: Optional[bool] = None
    """
    Whether Rupy should attempt to use Jinja templating to add context variables into the unit
    """
    status: Optional[Status] = None
    """
    Status of the unit.
    """
    type: Literal["5#-datamodel-code-generator-#-object-#-special-#"]
    reason: str
    """
    JSON string with validation/hydration details: { error, json, schema }
    """


class WorkflowSubworkflowUnitSchema(
    RootModel[
        Union[
            DataIOUnitSchema,
            ConditionUnitSchema,
            AssertionUnitSchema,
            ExecutionUnitSchema,
            AssignmentUnitSchema,
            ErrorUnitSchema,
        ]
    ]
):
    root: Union[
        DataIOUnitSchema,
        ConditionUnitSchema,
        AssertionUnitSchema,
        ExecutionUnitSchema,
        AssignmentUnitSchema,
        ErrorUnitSchema,
    ] = Field(..., discriminator="type", title="workflow subworkflow unit schema")


class Functional(Enum):
    pz = "pz"
    pw = "pw"
    vwn = "vwn"
    other = "other"


class Data(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    searchText: Optional[str] = None


class BaseMethod(BaseModel):
    type: str
    """
    general type of this method, eg. `pseudopotential`
    """
    subtype: str
    """
    general subtype of this method, eg. `ultra-soft`
    """
    precision: Optional[Dict[str, Any]] = None
    """
    Object showing the actual possible precision based on theory and implementation
    """
    data: Optional[Data] = None
    """
    additional data specific to method, eg. array of pseudopotentials
    """


class DFTLDAModelSchema(BaseModel):
    type: Literal["dft"]
    subtype: Literal["0#-datamodel-code-generator-#-object-#-special-#"]
    functional: Functional
    method: BaseMethod = Field(..., title="base method")


class Functional66(Enum):
    pbe = "pbe"
    pbesol = "pbesol"
    pw91 = "pw91"
    other = "other"


class BaseMethod51(BaseModel):
    type: str
    """
    general type of this method, eg. `pseudopotential`
    """
    subtype: str
    """
    general subtype of this method, eg. `ultra-soft`
    """
    precision: Optional[Dict[str, Any]] = None
    """
    Object showing the actual possible precision based on theory and implementation
    """
    data: Optional[Data] = None
    """
    additional data specific to method, eg. array of pseudopotentials
    """


class DFTGGAModelSchema(BaseModel):
    type: Literal["dft"]
    subtype: Literal["1#-datamodel-code-generator-#-object-#-special-#"]
    functional: Functional66
    method: BaseMethod51 = Field(..., title="base method")


class Functional67(Enum):
    b3lyp = "b3lyp"
    hse06 = "hse06"
    other = "other"


class BaseMethod52(BaseModel):
    type: str
    """
    general type of this method, eg. `pseudopotential`
    """
    subtype: str
    """
    general subtype of this method, eg. `ultra-soft`
    """
    precision: Optional[Dict[str, Any]] = None
    """
    Object showing the actual possible precision based on theory and implementation
    """
    data: Optional[Data] = None
    """
    additional data specific to method, eg. array of pseudopotentials
    """


class DFTHybridModelSchema(BaseModel):
    type: Literal["dft"]
    subtype: Literal["2#-datamodel-code-generator-#-object-#-special-#"]
    functional: Functional67
    method: BaseMethod52 = Field(..., title="base method")


class Type156(Enum):
    ml = "ml"


class Subtype31(Enum):
    re = "re"


class BaseMethod53(BaseModel):
    type: str
    """
    general type of this method, eg. `pseudopotential`
    """
    subtype: str
    """
    general subtype of this method, eg. `ultra-soft`
    """
    precision: Optional[Dict[str, Any]] = None
    """
    Object showing the actual possible precision based on theory and implementation
    """
    data: Optional[Data] = None
    """
    additional data specific to method, eg. array of pseudopotentials
    """


class MLModelSchema(BaseModel):
    type: Type156
    subtype: Literal["3#-datamodel-code-generator-#-object-#-special-#"]
    method: BaseMethod53 = Field(..., title="base method")


class Type157(Enum):
    unknown = "unknown"


class Subtype32(Enum):
    unknown = "unknown"


class BaseMethod54(BaseModel):
    type: str
    """
    general type of this method, eg. `pseudopotential`
    """
    subtype: str
    """
    general subtype of this method, eg. `ultra-soft`
    """
    precision: Optional[Dict[str, Any]] = None
    """
    Object showing the actual possible precision based on theory and implementation
    """
    data: Optional[Data] = None
    """
    additional data specific to method, eg. array of pseudopotentials
    """


class UnknownModelSchema(BaseModel):
    type: Type157
    subtype: Literal["4#-datamodel-code-generator-#-object-#-special-#"]
    method: BaseMethod54 = Field(..., title="base method")


class ApplicationSchema21(BaseModel):
    id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: str
    """
    entity name
    """
    isDefault: Optional[bool] = False
    """
    Identifies that entity is defaultable
    """
    shortName: str
    """
    The short name of the application. e.g. qe
    """
    summary: str
    """
    Application's short description.
    """
    version: str
    """
    Application version. e.g. 5.3.5
    """
    build: str
    """
    Application build. e.g. VTST
    """
    isDefaultVersion: Optional[bool] = None
    """
    Whether the version is the default version
    """
    hasAdvancedComputeOptions: Optional[bool] = None
    """
    Whether advanced compute options are present
    """
    isLicensed: Optional[bool] = None
    """
    Whether licensing is present
    """
    isUsingMaterial: Optional[bool] = None
    """
    Whether the application is using (being passed during a downstream processing routine) a material structure.
    """
    runConfig: Optional[RunConfig] = None
    """
    The run configuration of the application
    """


class SubworkflowSchema(BaseModel):
    id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: str
    """
    entity name
    """
    properties: List[str]
    """
    Array of characteristic properties calculated by this subworkflow
    """
    compute: Optional[ComputeArgumentsSchema17] = Field(None, title="compute arguments schema")
    """
    Compute schema
    """
    units: List[WorkflowSubworkflowUnitSchema]
    """
    Contains the Units of the subworkflow
    """
    model: Union[DFTLDAModelSchema, DFTGGAModelSchema, DFTHybridModelSchema, MLModelSchema, UnknownModelSchema] = Field(
        ..., discriminator="subtype", title="Any model schema"
    )
    application: ApplicationSchema21 = Field(..., title="application schema")
    isMultiMaterial: Optional[bool] = None
    isDraft: Optional[bool] = False
    """
    Defines whether to store the results/properties extracted in this unit to properties collection
    """


class Input19(BaseModel):
    target: str
    """
    Name of the target variable to substitute using the values below. e.g. K_POINTS
    """
    scope: Optional[str] = None
    """
    Scope to retrieve `values` from, global or flowchartId. Optional if `values` is given.
    """
    name: Optional[str] = None
    """
    Name of the variable inside the scope to retrieve `values` from. Optional if `values` is given.
    """
    values: Optional[List[Union[str, float, Dict[str, Any]]]] = None
    """
    Sequence of values for the target Jinja variable. Optional if `scope` and `name` are given. This can be used for map-reduce type parallel execution
    """
    useValues: Optional[bool] = None


class MapUnitSchema(BaseModel):
    id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: str
    """
    entity name
    """
    isDefault: Optional[bool] = False
    """
    Identifies that entity is defaultable
    """
    preProcessors: List[RuntimeItemNameObjectSchema]
    """
    names of the pre-processors for this calculation
    """
    postProcessors: List[RuntimeItemNameObjectSchema]
    """
    names of the post-processors for this calculation
    """
    monitors: List[RuntimeItemNameObjectSchema]
    """
    names of the monitors for this calculation
    """
    results: List[RuntimeItemNameObjectSchema]
    """
    names of the results for this calculation
    """
    tags: Optional[List[str]] = None
    """
    entity tags
    """
    statusTrack: Optional[List[StatusTrackItem]] = None
    isDraft: Optional[bool] = None
    head: Optional[bool] = None
    """
    Whether this unit is the first one to be executed.
    """
    flowchartId: str
    """
    Identity of the unit in the workflow. Used to trace the execution flow of the workflow.
    """
    next: Optional[str] = None
    """
    Next unit's flowchartId. If empty, the current unit is the last.
    """
    enableRender: Optional[bool] = None
    """
    Whether Rupy should attempt to use Jinja templating to add context variables into the unit
    """
    status: Optional[Status] = None
    """
    Status of the unit.
    """
    type: Literal["0#-datamodel-code-generator-#-object-#-special-#"]
    workflowId: str
    """
    Id of workflow to run inside map
    """
    input: Input19
    """
    Input information for map.
    """


class InputItem(BaseModel):
    operation: str
    """
    reduce operation, e.g. aggregate
    """
    arguments: List[str]
    """
    arguments which are passed to reduce operation function
    """


class ReduceUnitSchema(BaseModel):
    id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: str
    """
    entity name
    """
    isDefault: Optional[bool] = False
    """
    Identifies that entity is defaultable
    """
    preProcessors: List[RuntimeItemNameObjectSchema]
    """
    names of the pre-processors for this calculation
    """
    postProcessors: List[RuntimeItemNameObjectSchema]
    """
    names of the post-processors for this calculation
    """
    monitors: List[RuntimeItemNameObjectSchema]
    """
    names of the monitors for this calculation
    """
    results: List[RuntimeItemNameObjectSchema]
    """
    names of the results for this calculation
    """
    tags: Optional[List[str]] = None
    """
    entity tags
    """
    statusTrack: Optional[List[StatusTrackItem]] = None
    isDraft: Optional[bool] = None
    head: Optional[bool] = None
    """
    Whether this unit is the first one to be executed.
    """
    flowchartId: str
    """
    Identity of the unit in the workflow. Used to trace the execution flow of the workflow.
    """
    next: Optional[str] = None
    """
    Next unit's flowchartId. If empty, the current unit is the last.
    """
    enableRender: Optional[bool] = None
    """
    Whether Rupy should attempt to use Jinja templating to add context variables into the unit
    """
    status: Optional[Status] = None
    """
    Status of the unit.
    """
    type: Literal["1#-datamodel-code-generator-#-object-#-special-#"]
    mapFlowchartId: str
    """
    corresponding map unit flowchart ID
    """
    input: List[InputItem]
    """
    input information for reduce unit
    """


class SubworkflowUnitSchema(BaseModel):
    id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: str
    """
    entity name
    """
    isDefault: Optional[bool] = False
    """
    Identifies that entity is defaultable
    """
    preProcessors: List[RuntimeItemNameObjectSchema]
    """
    names of the pre-processors for this calculation
    """
    postProcessors: List[RuntimeItemNameObjectSchema]
    """
    names of the post-processors for this calculation
    """
    monitors: List[RuntimeItemNameObjectSchema]
    """
    names of the monitors for this calculation
    """
    results: List[RuntimeItemNameObjectSchema]
    """
    names of the results for this calculation
    """
    tags: Optional[List[str]] = None
    """
    entity tags
    """
    statusTrack: Optional[List[StatusTrackItem]] = None
    isDraft: Optional[bool] = None
    head: Optional[bool] = None
    """
    Whether this unit is the first one to be executed.
    """
    flowchartId: str
    """
    Identity of the unit in the workflow. Used to trace the execution flow of the workflow.
    """
    next: Optional[str] = None
    """
    Next unit's flowchartId. If empty, the current unit is the last.
    """
    enableRender: Optional[bool] = None
    """
    Whether Rupy should attempt to use Jinja templating to add context variables into the unit
    """
    status: Optional[Status] = None
    """
    Status of the unit.
    """
    type: Literal["2#-datamodel-code-generator-#-object-#-special-#"]


class ErrorUnitSchema16(BaseModel):
    id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: str
    """
    entity name
    """
    isDefault: Optional[bool] = False
    """
    Identifies that entity is defaultable
    """
    preProcessors: List[RuntimeItemNameObjectSchema]
    """
    names of the pre-processors for this calculation
    """
    postProcessors: List[RuntimeItemNameObjectSchema]
    """
    names of the post-processors for this calculation
    """
    monitors: List[RuntimeItemNameObjectSchema]
    """
    names of the monitors for this calculation
    """
    results: List[RuntimeItemNameObjectSchema]
    """
    names of the results for this calculation
    """
    tags: Optional[List[str]] = None
    """
    entity tags
    """
    statusTrack: Optional[List[StatusTrackItem]] = None
    isDraft: Optional[bool] = None
    head: Optional[bool] = None
    """
    Whether this unit is the first one to be executed.
    """
    flowchartId: str
    """
    Identity of the unit in the workflow. Used to trace the execution flow of the workflow.
    """
    next: Optional[str] = None
    """
    Next unit's flowchartId. If empty, the current unit is the last.
    """
    enableRender: Optional[bool] = None
    """
    Whether Rupy should attempt to use Jinja templating to add context variables into the unit
    """
    status: Optional[Status] = None
    """
    Status of the unit.
    """
    type: Literal["3#-datamodel-code-generator-#-object-#-special-#"]
    reason: str
    """
    JSON string with validation/hydration details: { error, json, schema }
    """


class WorkflowUnitSchema(RootModel[Union[MapUnitSchema, ReduceUnitSchema, SubworkflowUnitSchema, ErrorUnitSchema16]]):
    root: Union[MapUnitSchema, ReduceUnitSchema, SubworkflowUnitSchema, ErrorUnitSchema16] = Field(
        ..., discriminator="type", title="workflow unit schema"
    )


class Application(BaseModel):
    name: Optional[str] = None
    """
    name of the application
    """


class WorkflowPropertySchema(BaseModel):
    name: Name
    """
    entity name
    """
    workflows: List[Dict[str, Any]]
    """
    Array of workflows with the same schema as the current one.
    """
    compute: Optional[ComputeArgumentsSchema] = Field(None, title="compute arguments schema")
    """
    Compute schema
    """
    id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    metadata: Optional[Dict[str, Any]] = None
    properties: List[str]
    """
    Array of characteristic properties calculated by this workflow (TODO: add enums)
    """
    isUsingDataset: Optional[bool] = None
    """
    Whether to use the dataset tab in the job designer. Mutually exclusive with using the materials tab.
    """
    isMultiMaterial: Optional[bool] = None
    """
    Defines whether the workflow is for a multi-material simulation
    """
    subworkflows: List[SubworkflowSchema]
    """
    Array of subworkflows. Subworkflow can be an instance of workflow to allow for nesting
    """
    units: List[WorkflowUnitSchema]
    """
    Contains the Units of the Workflow
    """
    application: Optional[Application] = None
    """
    information about the main application used for workflow categorization by application in standata.
    """
    tags: Optional[List[str]] = None
    """
    tags for the workflow
    """
    description: Optional[str] = None
    """
    entity description
    """
    descriptionObject: Optional[Dict[str, Any]] = None
