# generated by datamodel-codegen:
#   filename:  core/reusable/combined_value.json
#   version:   0.28.5

from __future__ import annotations

from pydantic import BaseModel


class CombinedValueSchema(BaseModel):
    value: float
    """
    mean over the combined measurements
    """
    standardDeviation: float
    """
    population standard deviation over the combined measurements (not the standard error of the mean)
    """
    count: int
    """
    number of measurements combined
    """
