# generated by datamodel-codegen:
#   filename:  core/reusable/field_condition.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum


class FieldConditionSchema(Enum):
    on = "on"
    off = "off"
