# generated by datamodel-codegen:
#   filename:  core/reusable/hysteresis_loop_parameters.json
#   version:   0.28.5

from __future__ import annotations

from pydantic import BaseModel, Field


class CombinedValueSchema(BaseModel):
    value: float
    """
    mean over the combined measurements
    """
    standardDeviation: float
    """
    population standard deviation over the combined measurements (not the standard error of the mean)
    """
    count: int
    """
    number of measurements combined
    """


class CoerciveVoltage(BaseModel):
    rising: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    A value combined over repeated measurements: mean, standard deviation, count. Units come from the context the value appears in
    """
    falling: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    A value combined over repeated measurements: mean, standard deviation, count. Units come from the context the value appears in
    """


class RemanentResponse(BaseModel):
    rising: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    A value combined over repeated measurements: mean, standard deviation, count. Units come from the context the value appears in
    """
    falling: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    A value combined over repeated measurements: mean, standard deviation, count. Units come from the context the value appears in
    """


class HysteresisLoopParametersSchema(BaseModel):
    imprint: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    bias at the centre of the loop: half the sum of the two coercive voltages
    """
    coerciveVoltage: CoerciveVoltage
    """
    bias at which the response crosses the loop's offset, on the rising and the falling branch
    """
    loopWidth: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    bias separation of the two coercive voltages
    """
    loopHeight: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    response separation of the two remanent responses
    """
    remanentResponse: RemanentResponse
    """
    response at zero bias, on the rising and the falling branch
    """


class BranchPair(BaseModel):
    rising: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    A value combined over repeated measurements: mean, standard deviation, count. Units come from the context the value appears in
    """
    falling: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    A value combined over repeated measurements: mean, standard deviation, count. Units come from the context the value appears in
    """
