# generated by datamodel-codegen:
#   filename:  properties_directory/scalar/homo_energy.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Union

from pydantic import BaseModel


class Name(Enum):
    homo_energy = "homo_energy"


class Units(Enum):
    kcal_mol = "kcal/mol"
    kJ_mol = "kJ/mol"
    eV = "eV"
    J_mol = "J/mol"
    hartree = "hartree"
    cm_1 = "cm-1"
    Ry = "Ry"
    eV_atom = "eV/atom"


class Units259(Enum):
    eV_A_2 = "eV/A^2"


class HOMOEnergyPropertySchema(BaseModel):
    name: Name
    units: Union[Units, Units259]
    value: float
