#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

SRC_PATTERN="\.json$"
if git diff --cached --name-only | grep --quiet -E "$SRC_PATTERN"
then
  echo "JSON assets changed. Running build scripts."
  echo "Re-building JS and PY assets using JS script."
  npm run build:js-and-python-modules
fi

npx lint-staged
