#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

SRC_PATTERN="\.json$"
if git diff --cached --name-only | grep --quiet -E "$SRC_PATTERN"
then
  echo "JSON assets changed. Running build scripts."
  echo "Re-building JS assets."
  npm run build:assets
  echo "Re-building Python assets: requires virtual environment and dependencies (pip install .'[tests]')."
  python build_schemas.py
fi

npx lint-staged
