# generated by datamodel-codegen:
#   filename:  measurement/set.json
#   version:   0.28.5

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class EntityReferenceSchema(BaseModel):
    id: str = Field(..., alias="_id")
    """
    entity identity
    """
    cls: Optional[str] = None
    """
    entity class
    """
    slug: Optional[str] = None
    """
    entity slug
    """


class MeasurementSetSchema(BaseModel):
    sampleSet: Optional[EntityReferenceSchema] = Field(None, alias="_sampleSet", title="entity reference schema")
    isEntitySet: Optional[bool] = None
    entitySetType: Optional[str] = None
    entityCls: Optional[str] = None
