# generated by datamodel-codegen:
#   filename:  measurement/setup.json
#   version:   0.28.5

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, Optional

from pydantic import BaseModel


class Session(BaseModel):
    name: Optional[str] = None
    started: Optional[datetime] = None
    finished: Optional[datetime] = None
    operator: Optional[str] = None
    directory: Optional[str] = None
    """
    Where the instrument wrote its raw data
    """


class MeasurementSetupSchema(BaseModel):
    name: str
    """
    Identity of the instrument, as a cluster's fqdn identifies a cluster
    """
    description: Optional[Dict[str, Any]] = None
    """
    Vendor, model, serial and whatever else describes the machine
    """
    session: Optional[Session] = None
    """
    The sitting during which the measurement was taken
    """
    settings: Optional[Dict[str, Any]] = None
    """
    Instrument parameters as set for this measurement
    """
    environment: Optional[Dict[str, Any]] = None
    """
    Conditions during the measurement: temperature, pressure, atmosphere
    """
    registration: Optional[Dict[str, Any]] = None
    """
    How the instrument frame maps onto the sample: frame, anchor, coordinates
    """
