# generated by datamodel-codegen:
#   filename:  core/reference/external.json
#   version:   0.28.5

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class ESSE(BaseModel):
    measurementId: str
    """
    Measurement's identity
    """
    sampleId: Optional[str] = None
    """
    Identity of the sample the result is about
    """
    unitId: str
    """
    Id of the unit that extracted the result
    """
