name: Node.js Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - uses: actions/setup-node@v1
      with:
        node-version: '8.11.x'
        registry-url: 'https://registry.npmjs.org'

    - run: npm install

    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
